/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.technisha.exampleplugin;

import kr.entree.spigradle.annotations.SpigotPlugin;

import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

@SpigotPlugin
public class Main extends JavaPlugin {
    @Override
    public void onDisable() {
    }

    @Override
    public void onEnable() {
        Bukkit.broadcastMessage("Server started!");
    }
}
